dist: xenial
sudo: false

language: node_js
node_js:
  - "7"

install:
  - npm install babel-register --save-dev
  - npm install babel-preset-env --save-dev
  - npm install --save babel-polyfill
  - npm install -g truffle
  - npm install chai
  - npm install chai-as-promised
  - npm install --save-dev chai-bignumber
  - npm install zeppelin-solidity
  - npm install -g ethereumjs-testrpc
  - npm install -g web3

before_script:
  - testrpc > testrpc.log &

script:
  - truffle test

